export const names_unicorns_ua = [
  'Аметист',
  'Аврора',
  'Блісс',
  'Валькірія',
  'Гвіневра',
  'Гая',
  'Гавріїл',
  'Діана',
  'Ельза',
  'Емеральд',
  'Єва',
  'Жасмін',
  'Зефір',
  'Зірафа',
  'Ілларія',
  'Ірида',
  'Ізольда',
  'Імеда',
  'Йоган',
  'Каліпсо',
  'Каріна',
  'сніг',
  'Лумін',
  'Маделін',
  'Магія',
  'Мелодія',
  'Мірабел',
  'Німфа',
  'Ніка',
  'Олівія',
  'Пандора',
  'Перла',
  'Роксан',
  'Рубін',
  'Сабріна',
  'Селестія',
  'Сільвія',
  'Твіл',
  'Талісман',
  'Урсула',
  'Фея',
  'Флора',
  'Хармонія',
  'Цезар',
  'кавун',
  'Шарлотт',
  'Шиммер',
  'Щаст',
  'Юлі',
  'Ясна',
  'Ясмін',
  'Ягод',
  'Ярк',
  'Яр',
  'Явор',
  'Яскрав',
  'Ярослав',
  'Якір',
  'Яворон',
  'Янік',
  'Ярем',
  'Яхонт',
  'Ярославна',
  'Ярославіт',
  'Айріс',
  'Блейз',
  'Корал',
  'Ділан',
  'Ензо',
  'Флін',
  'Гарет',
  'Харпер',
  'лаванда',
  'Джейд',
  'Кайл',
  'Леон',
  'Майкл',
  'Ноа',
  'Олівер',
  'Пенелопа',
  'Раян',
  'Софія',
  'Тревор',
  'Уїллоу',
  'Ягідниц',
  'Ягідниця',
  'Лиса',
  'Зайд',
  'Варун',
  'Нана',
];
export const names_unicorns_en = [
  'Amethyst',
  'Aurora',
  'Bliss',
  'Valkyrie',
  'Guinevere',
  'Gaia',
  'Gabriel',
  'Diana',
  'Elsa',
  'Emerald',
  'Eva',
  'Jasmine',
  'Zephyr',
  'Zirafa',
  'Hilary',
  'Iris',
  'Isolde',
  'Imeda',
  'Johan',
  'Calypso',
  'Karina',
  'snow',
  'Lumine',
  'Madeline',
  'Magic',
  'Melody',
  'Mirabel',
  'Nymph',
  'Nika',
  'Olivia',
  'Pandora',
  'Pearl',
  'Roxane',
  'Ruby',
  'Sabrina',
  'Celestia',
  'Sylvia',
  'Twilight',
  'Talisman',
  'Ursula',
  'Fairy',
  'Flora',
  'Harmony',
  'Caesar',
  'Watermalon',
  'Charlotte',
  'Shimmer',
  'Luck',
  'Julia',
  'Yasna',
  'Jasmine',
  'Berry',
  'Bright',
  'Ray',
  'Maple',
  'Shining',
  'Yaroslav',
  'Anchor',
  'Raven',
  'Yanic',
  'Jeremy',
  'Jacinth',
  'Yaroslavna',
  'Yaroslavite',
  'Iris',
  'Blaze',
  'Coral',
  'Dylan',
  'Enzo',
  'Flynn',
  'Garrett',
  'Harper',
  'lavander',
  'Jade',
  'Kyle',
  'Leon',
  'Michael',
  'Noah',
  'Oliver',
  'Penelope',
  'Ryan',
  'Sophia',
  'Trevor',
  'Willow',
  'Berry',
  'Berrylicious',
  'Fox',
  'Zayd',
  'Varun',
  'Тana',
];
export const gender = [
  0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1,
  0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0,
  0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0,
  1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1,
];
export const style = ["crystal","ma"];
// function getDuplicateIndexes(arr) {
//   var duplicateIndexes = [];

//   for (var i = 0; i < arr.length; i++) {
//     for (var j = i + 1; j < arr.length; j++) {
//       if (arr[i] === arr[j]) {
//         if (!duplicateIndexes.includes(i)) {
//           duplicateIndexes.push(i);
//         }
//         if (!duplicateIndexes.includes(j)) {
//           duplicateIndexes.push(j);
//         }
//       }
//     }
//   }

//   return duplicateIndexes;
// }

// // Приклад використання

// var duplicateIndexes = getDuplicateIndexes(names_unicorns);
// console.log(duplicateIndexes); // Виведе [1, 3], оскільки рядки "рядок2" повторюються на індексах 1 і 3

// console.log(names_unicorns.length);
