export default unicorns_items = [
  {
    name: 'Iris',
    age: 675,
    gender: 'male',
    style: '',
    cost: 250000,
    img: '../img/unicorn(1).png',
  },
  {
    name: 'Mystique',
    age: 456,
    gender: 'female',
    style: '',
    cost: 45000,
    img: '../img/unicorn(2).png',
  },
  {
    name: 'Luna',
    age: 834,
    gender: 'female',
    style: '',
    cost: 72000,
    img: '../img/unicorn(3).png',
  },
  {
    name: 'Celestia',
    age: 245,
    gender: 'female',
    style: '',
    cost: 31000,
    img: 'unicorn (4)',
  },
  {
    name: 'Apollo',
    age: 567,
    gender: 'male',
    style: '',
    cost: 89000,
    img: 'unicorn (5)',
  },
  {
    name: 'Stardust',
    age: 712,
    gender: 'female',
    style: '',
    cost: 54000,
    img: 'unicorn (6)',
  },
  {
    name: 'Thunder',
    age: 389,
    gender: 'male',
    style: '',
    cost: 18000,
    img: 'unicorn (7)',
  },
  {
    name: 'Novaya',
    age: 926,
    gender: 'female',
    style: '',
    cost: 96000,
    img: 'unicorn (8)',
  },
  {
    name: 'Blaze',
    age: 173,
    gender: 'male',
    style: '',
    cost: 15000,
    img: 'unicorn (9)',
  },
  {
    name: 'Aurora',
    age: 512,
    gender: 'female',
    style: '',
    cost: 32000,
    img: 'unicorn (10)',
  },
  {
    name: 'Shadow',
    age: 648,
    gender: 'male',
    style: '',
    cost: 78000,
    img: 'unicorn (11)',
  },
  {
    name: 'Lily',
    age: 287,
    gender: 'female',
    style: '',
    cost: 41000,
    img: 'unicorn (12)',
  },
  {
    name: 'Spirit',
    age: 731,
    gender: 'male',
    style: '',
    cost: 62000,
    img: 'unicorn (13)',
  },
  {
    name: 'Pearl',
    age: 429,
    gender: 'female',
    style: '',
    cost: 56000,
    img: 'unicorn (14)',
  },
  {
    name: 'Storm',
    age: 567,
    gender: 'male',
    style: '',
    cost: 23000,
    img: 'unicorn (15)',
  },
  {
    name: 'Crystal',
    age: 825,
    gender: 'female',
    style: '',
    cost: 79000,
    img: 'unicorn (16)',
  },
  {
    name: 'Midnight',
    age: 193,
    gender: 'male',
    style: '',
    cost: 26000,
    img: 'unicorn (17)',
  },
  {
    name: 'Sapphire',
    age: 385,
    gender: 'female',
    style: '',
    cost: 37000,
    img: 'unicorn (18)',
  },
  {
    name: 'Thunderbolt',
    age: 712,
    gender: 'male',
    style: '',
    cost: 84000,
    img: 'unicorn (19)',
  },
  {
    name: 'Rainbow',
    age: 281,
    gender: 'female',
    style: '',
    cost: 44000,
    img: 'unicorn (20)',
  },
  {
    name: 'Lucky',
    age: 521,
    gender: 'male',
    style: '',
    cost: 27000,
    img: 'unicorn (21)',
  },
  {
    name: 'Diamond',
    age: 936,
    gender: 'female',
    style: '',
    cost: 93000,
    img: 'unicorn (22)',
  },
  {
    name: 'Diamond',
    age: 936,
    gender: 'female',
    style: '',
    cost: 93000,
    img: 'unicorn (22)',
  },
  {
    name: 'Stellar',
    age: 587,
    gender: 'male',
    style: '',
    cost: 56000,
    img: 'unicorn (23)',
  },
  {
    name: 'Twilight',
    age: 215,
    gender: 'female',
    style: '',
    cost: 32000,
    img: 'unicorn (24)',
  },
  {
    name: 'Cosmo',
    age: 459,
    gender: 'male',
    style: '',
    cost: 48000,
    img: 'unicorn (25)',
  },
  {
    name: 'Nova',
    age: 784,
    gender: 'female',
    style: '',
    cost: 67000,
    img: 'unicorn (26)',
  },
];
